export { default as Main } from './main'
export { default as Login } from './login'
export { default as Register } from './register'
export { default as Navbar } from './navbar'
export { default as ArticleDetail } from './article-detail'
export { default as FormControl } from './article-form'
export { default as EditArticle } from './edit-article'
export { default as Profile } from './profile'